# Generated by Django 2.0.6 on 2018-06-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180626_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='some',
            old_name='tite',
            new_name='title',
        ),
    ]
