# Generated by Django 2.0.6 on 2018-06-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180626_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='some',
            name='title',
            field=models.SlugField(max_length=200),
        ),
    ]
